auditbeat.modules:
- module: file_integrity
  paths:
    - /bin

setup.template.enabled: true
setup.template.name: "auditbeat-%{[agent.version]}"
setup.template.pattern: "auditbeat-%{[agent.version]}-*"
setup.template.overwrite: false

setup.ilm.enabled: false
#setup.ilm.enabled: auto
#setup.ilm.rollover_alias: "auditbeat-%{[agent.version]}"
#setup.ilm.pattern: "{now/d}-000001"
#setup.ilm.policy_name: "auditbeat"
#setup.ilm.check_exists: true
#setup.ilm.overwrite: true

setup.kibana:
  host: "${KIBANA_HOST}:${KIBANA_PORT}"
  protocol: https
  username: "${KIBANA_USERNAME}"
  password: "${KIBANA_PASSWORD}"
  ssl.certificate_authorities:
    - "/usr/share/auditbeat/certs/ca.crt"
  ssl.enabled: true

output.elasticsearch:
  enabled: true
  hosts: ["${ELASTIC_HOST}:${ELASTIC_PORT}"]
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"
  ssl.certificate_authorities:
    - "/usr/share/auditbeat/certs/ca.crt"
  index: "auditbeat-%{[agent.version]}"
  protocol: https
  ssl.enabled: true
